export const headerStyles = {
  announcement: {
    bgcolor: "secondary.main",
    color: "secondary.contrastText",
  },
  announcementInner: {
    minHeight: 38,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
  },
  announcementItem: {
    display: "flex",
    alignItems: "center",
    gap: 0.75,
    color: "inherit",
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textDecoration: "none",
    textTransform: "uppercase",
  },
  addressItem: {
    display: { xs: "none", sm: "flex" },
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 1100,
    borderBottom: "1px solid",
    borderColor: "rgba(36, 69, 58, 0.12)",
    bgcolor: "rgba(255, 253, 247, 0.95)",
    backdropFilter: "blur(14px)",
  },
  nav: {
    minHeight: { xs: 72, md: 84 },
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 3,
  },
  brand: {
    display: "flex",
    alignItems: "center",
    gap: 1.5,
    color: "primary.dark",
    textDecoration: "none",
  },
  brandMark: {
    width: 42,
    height: 42,
    display: "grid",
    placeItems: "center",
    border: "1px solid",
    borderColor: "primary.main",
    borderRadius: "50%",
    color: "primary.main",
    transform: "rotate(-3deg)",
  },
  brandName: {
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "0.92rem", sm: "1rem" },
    fontWeight: 700,
    letterSpacing: "-0.02em",
    lineHeight: 1.15,
  },
  brandLocation: {
    display: { xs: "none", sm: "block" },
    mt: 0.25,
    color: "text.secondary",
    fontSize: "0.64rem",
    fontWeight: 700,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  desktopNav: {
    display: { xs: "none", md: "flex" },
    alignItems: "center",
    gap: 0.5,
  },
  navLink: {
    px: 1.35,
    color: "text.primary",
    fontSize: "0.84rem",
    fontWeight: 700,
    textDecoration: "none",
    "&:hover": {
      color: "secondary.main",
    },
  },
  giveButton: {
    ml: 1,
    minHeight: 42,
    px: 2.25,
  },
  menuButton: {
    display: { xs: "inline-flex", md: "none" },
    color: "primary.dark",
  },
  drawerPaper: {
    width: "min(86vw, 360px)",
    bgcolor: "background.default",
    backgroundImage:
      "linear-gradient(rgba(36, 69, 58, 0.04) 1px, transparent 1px)",
    backgroundSize: "100% 28px",
  },
  drawerInner: {
    height: "100%",
    p: 3,
    display: "flex",
    flexDirection: "column",
  },
  drawerTop: {
    mb: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  drawerNav: {
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
  },
  drawerLink: {
    py: 1.6,
    borderBottom: "1px solid",
    borderColor: "divider",
    color: "text.primary",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: "1.5rem",
    fontWeight: 600,
    textDecoration: "none",
  },
  drawerGive: {
    mt: "auto",
  },
} as const;
