export const styles = {
  header: {
    bgcolor: "rgba(247, 245, 237, 0.94)",
    borderBottom: "1px solid rgba(29, 75, 53, 0.1)",
    position: "sticky",
    top: 0,
    zIndex: 30,
    backdropFilter: "blur(14px)",
  },
  utilityBar: {
    bgcolor: "primary.dark",
    color: "rgba(255, 255, 255, 0.8)",
    display: { xs: "none", md: "block" },
    fontSize: "0.72rem",
    fontWeight: 700,
    letterSpacing: "0.04em",
  },
  utilityContent: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: "34px",
  },
  utilityItem: {
    alignItems: "center",
    color: "inherit",
    display: "inline-flex",
    gap: 0.75,
    textDecoration: "none",
    "& svg": {
      color: "secondary.main",
      fontSize: "0.95rem",
    },
  },
  nav: {
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    minHeight: { xs: "74px", md: "82px" },
  },
  brand: {
    alignItems: "center",
    color: "text.primary",
    display: "flex",
    gap: 1.25,
    textDecoration: "none",
  },
  logo: {
    height: { xs: "45px", md: "54px" },
    objectFit: "contain",
    width: { xs: "50px", md: "59px" },
  },
  brandName: {
    fontFamily: '"Iowan Old Style", "Baskerville", Georgia, serif',
    fontSize: { xs: "1.12rem", md: "1.28rem" },
    fontWeight: 700,
    lineHeight: 1,
  },
  brandDetail: {
    color: "text.secondary",
    display: "block",
    fontFamily:
      '"Helvetica Neue", "Segoe UI", -apple-system, BlinkMacSystemFont, Arial, sans-serif',
    fontSize: "0.56rem",
    fontWeight: 800,
    letterSpacing: "0.14em",
    mt: 0.5,
    textTransform: "uppercase",
  },
  desktopNav: {
    alignItems: "center",
    display: { xs: "none", md: "flex" },
    gap: { md: 2.5, lg: 4 },
  },
  navLink: {
    color: "text.primary",
    fontSize: "0.86rem",
    fontWeight: 700,
    position: "relative",
    textDecoration: "none",
    "&::after": {
      bgcolor: "secondary.main",
      bottom: "-8px",
      content: '""',
      height: "2px",
      left: 0,
      position: "absolute",
      transform: "scaleX(0)",
      transformOrigin: "left",
      transition: "transform 180ms ease",
      width: "100%",
    },
    "&:hover::after": {
      transform: "scaleX(1)",
    },
  },
  quoteButton: {
    borderRadius: "999px",
    minHeight: "46px",
    px: 2.5,
  },
  mobileButton: {
    border: "1px solid rgba(29, 75, 53, 0.2)",
    color: "primary.main",
    display: { xs: "inline-flex", md: "none" },
  },
  mobileMenu: {
    bgcolor: "background.default",
    borderTop: "1px solid rgba(29, 75, 53, 0.1)",
    display: { xs: "block", md: "none" },
  },
  mobileMenuInner: {
    display: "flex",
    flexDirection: "column",
    gap: 0.5,
    pb: 3,
    pt: 1.5,
  },
  mobileLink: {
    borderBottom: "1px solid rgba(29, 75, 53, 0.1)",
    color: "text.primary",
    fontFamily: '"Iowan Old Style", "Baskerville", Georgia, serif',
    fontSize: "1.5rem",
    fontWeight: 600,
    py: 1.5,
    textDecoration: "none",
  },
  mobileActions: {
    display: "grid",
    gap: 1,
    gridTemplateColumns: "1fr 1fr",
    mt: 2,
  },
};
