export const heroStyles = {
  section: {
    position: "relative",
    overflow: "hidden",
    bgcolor: "primary.dark",
    color: "primary.contrastText",
  },
  grid: {
    minHeight: { xs: "auto", md: 690, lg: 740 },
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      md: "minmax(0, 0.92fr) minmax(0, 1.08fr)",
    },
  },
  content: {
    position: "relative",
    zIndex: 2,
    px: { xs: 3, sm: 6, md: "max(5vw, calc((100vw - 1200px) / 2))" },
    pt: { xs: 8, sm: 10, md: 11 },
    pb: { xs: 9, md: 15 },
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    backgroundImage:
      "radial-gradient(circle at 14% 20%, rgba(255,255,255,0.06) 0 1px, transparent 1px)",
    backgroundSize: "18px 18px",
  },
  eyebrow: {
    display: "flex",
    alignItems: "center",
    gap: 1.25,
    mb: 3,
    color: "#E8A27A",
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    "&::before": {
      width: 34,
      height: 2,
      bgcolor: "currentColor",
      content: '""',
    },
  },
  title: {
    maxWidth: 650,
    mb: 3,
    color: "#FFF9EE",
    fontSize: { xs: "3.35rem", sm: "4.6rem", md: "4.7rem", lg: "5.45rem" },
    lineHeight: 0.98,
  },
  titleAccent: {
    color: "#E8A27A",
    fontStyle: "italic",
  },
  description: {
    maxWidth: 570,
    mb: 4.5,
    color: "rgba(255, 249, 238, 0.74)",
    fontSize: { xs: "1.02rem", md: "1.13rem" },
    lineHeight: 1.75,
  },
  actions: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1.5,
  },
  primaryAction: {
    bgcolor: "secondary.main",
    "&:hover": {
      bgcolor: "#C86B47",
    },
  },
  secondaryAction: {
    borderColor: "rgba(255, 249, 238, 0.5)",
    color: "#FFF9EE",
    "&:hover": {
      borderColor: "#FFF9EE",
      bgcolor: "rgba(255, 255, 255, 0.06)",
    },
  },
  imageWrap: {
    position: "relative",
    minHeight: { xs: 430, sm: 530, md: "auto" },
    overflow: "hidden",
  },
  image: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
    objectPosition: { xs: "57% center", md: "53% center" },
    filter: "saturate(0.8) contrast(1.05)",
  },
  imageOverlay: {
    position: "absolute",
    inset: 0,
    background:
      "linear-gradient(90deg, rgba(23,51,43,0.3) 0%, transparent 28%), linear-gradient(0deg, rgba(12,25,21,0.3), transparent 45%)",
  },
  serviceBadge: {
    position: "absolute",
    right: { xs: 20, md: 42 },
    bottom: { xs: 22, md: 44 },
    width: { xs: 136, md: 156 },
    height: { xs: 136, md: 156 },
    p: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid rgba(255,255,255,0.42)",
    borderRadius: "50%",
    bgcolor: "rgba(184, 92, 56, 0.92)",
    boxShadow: "0 16px 50px rgba(17, 29, 25, 0.28)",
    color: "white",
    textAlign: "center",
    backdropFilter: "blur(8px)",
    transform: "rotate(3deg)",
  },
  badgeSmall: {
    fontSize: "0.65rem",
    fontWeight: 800,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
  },
  badgeTime: {
    my: 0.25,
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "1.55rem", md: "1.8rem" },
    fontWeight: 700,
  },
  values: {
    borderTop: "1px solid rgba(255, 249, 238, 0.14)",
    bgcolor: "#102C24",
  },
  valuesInner: {
    minHeight: { xs: 82, md: 92 },
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    alignItems: "center",
  },
  value: {
    px: { xs: 1, md: 3 },
    color: "rgba(255, 249, 238, 0.75)",
    fontSize: { xs: "0.67rem", sm: "0.83rem" },
    fontWeight: 700,
    letterSpacing: { xs: "0.04em", sm: "0.1em" },
    textAlign: "center",
    textTransform: "uppercase",
    "&:not(:last-of-type)": {
      borderRight: "1px solid rgba(255, 249, 238, 0.15)",
    },
  },
} as const;
