export const styles = {
  hero: {
    bgcolor: "background.default",
    overflow: "hidden",
    position: "relative",
  },
  heroInner: {
    display: "grid",
    gap: { xs: 4, md: 5, lg: 7 },
    gridTemplateColumns: {
      xs: "1fr",
      md: "minmax(0, 0.92fr) minmax(0, 1.08fr)",
    },
    minHeight: { md: "690px", lg: "760px" },
    py: { xs: 6, sm: 8, md: 7 },
  },
  content: {
    alignSelf: "center",
    maxWidth: "650px",
    py: { md: 7 },
    position: "relative",
    zIndex: 2,
  },
  eyebrow: {
    alignItems: "center",
    color: "primary.main",
    display: "flex",
    fontSize: "0.72rem",
    fontWeight: 800,
    gap: 1,
    letterSpacing: "0.16em",
    mb: 2.5,
    textTransform: "uppercase",
  },
  eyebrowDot: {
    bgcolor: "secondary.main",
    borderRadius: "50%",
    boxShadow: "0 0 0 6px rgba(217, 170, 85, 0.16)",
    height: "8px",
    width: "8px",
  },
  heading: {
    color: "text.primary",
    fontSize: { xs: "3.5rem", sm: "5rem", md: "5.25rem", lg: "6.5rem" },
    maxWidth: "680px",
  },
  headingAccent: {
    color: "primary.main",
    display: "block",
    fontStyle: "italic",
  },
  description: {
    color: "text.secondary",
    fontSize: { xs: "1.04rem", md: "1.16rem" },
    lineHeight: 1.75,
    maxWidth: "560px",
    mt: 3,
  },
  actions: {
    alignItems: { xs: "stretch", sm: "center" },
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    gap: { xs: 1.5, sm: 2 },
    mt: 4,
  },
  callLink: {
    alignItems: "center",
    color: "text.primary",
    display: "inline-flex",
    fontSize: "0.9rem",
    fontWeight: 800,
    gap: 1,
    justifyContent: { xs: "center", sm: "flex-start" },
    minHeight: "54px",
    px: 1,
    textDecoration: "none",
    "& svg": {
      color: "secondary.dark",
      fontSize: "1.15rem",
    },
  },
  imageWrap: {
    alignSelf: "stretch",
    borderRadius: { xs: "28px", md: "0 0 0 110px" },
    minHeight: { xs: "460px", sm: "560px", md: "auto" },
    overflow: "hidden",
    position: "relative",
  },
  image: {
    height: "100%",
    inset: 0,
    objectFit: "cover",
    position: "absolute",
    width: "100%",
  },
  imageOverlay: {
    background:
      "linear-gradient(180deg, rgba(18, 51, 36, 0.02) 45%, rgba(18, 51, 36, 0.72) 100%)",
    inset: 0,
    position: "absolute",
  },
  floatingCard: {
    alignItems: "center",
    backdropFilter: "blur(10px)",
    bgcolor: "rgba(255, 255, 255, 0.9)",
    border: "1px solid rgba(255, 255, 255, 0.7)",
    borderRadius: "20px",
    bottom: { xs: 20, md: 34 },
    display: "flex",
    gap: 1.5,
    left: { xs: 20, md: 34 },
    maxWidth: "315px",
    p: 2,
    position: "absolute",
  },
  floatingIcon: {
    alignItems: "center",
    bgcolor: "secondary.main",
    borderRadius: "50%",
    color: "primary.dark",
    display: "flex",
    flex: "0 0 auto",
    height: "46px",
    justifyContent: "center",
    width: "46px",
  },
  floatingTitle: {
    color: "primary.dark",
    fontSize: "0.92rem",
    fontWeight: 800,
    lineHeight: 1.3,
  },
  floatingCopy: {
    color: "text.secondary",
    fontSize: "0.72rem",
    lineHeight: 1.5,
    mt: 0.25,
  },
  trustRow: {
    borderTop: "1px solid rgba(29, 75, 53, 0.14)",
    display: "grid",
    gridTemplateColumns: { xs: "1fr 1fr", md: "repeat(4, 1fr)" },
  },
  trustItem: {
    borderRight: { md: "1px solid rgba(29, 75, 53, 0.14)" },
    py: { xs: 2.5, md: 3 },
    pr: { xs: 1, md: 3 },
    "&:last-of-type": {
      borderRight: "none",
    },
  },
  trustValue: {
    color: "primary.main",
    fontFamily: '"Iowan Old Style", "Baskerville", Georgia, serif',
    fontSize: { xs: "1.6rem", md: "2rem" },
    fontWeight: 600,
    lineHeight: 1,
  },
  trustLabel: {
    color: "text.secondary",
    fontSize: { xs: "0.66rem", md: "0.75rem" },
    fontWeight: 700,
    letterSpacing: "0.06em",
    mt: 0.75,
    textTransform: "uppercase",
  },
};
