import { alpha } from "@mui/material/styles";
import { BURGUNDY, CREAM, OCHRE, TRACKED_CAPS } from "@/theme";

export const homeHeroStyles = {
  root: {
    position: "relative",
    backgroundColor: BURGUNDY,
  },
  panel: {
    position: "relative",
    minHeight: { xs: "94svh", md: "100svh" },
    overflow: "hidden",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    backgroundColor: BURGUNDY,
    borderBottomLeftRadius: { xs: "0", md: "48% 5%" },
    borderBottomRightRadius: { xs: "0", md: "48% 5%" },
  },
  media: {
    position: "absolute",
    inset: 0,
    animation: "slowDrift 24s ease-in-out infinite alternate",
    "& picture, & img": { width: "100%", height: "100%", objectFit: "cover" },
  },
  scrim: {
    position: "absolute",
    inset: 0,
    background: `linear-gradient(to bottom, ${alpha(BURGUNDY, 0.28)} 0%, ${alpha(
      BURGUNDY,
      0.24,
    )} 32%, ${alpha(BURGUNDY, 0.92)} 100%)`,
  },
  content: {
    position: "relative",
    textAlign: "center",
    color: CREAM,
    px: { xs: 2.5, md: 5 },
    pb: { xs: 11, md: 10 },
    width: "100%",
    animation: "fadeIn 1400ms ease-out both",
  },
  eyebrow: {
    ...TRACKED_CAPS,
    fontSize: { xs: "0.68rem", md: "0.76rem" },
    fontWeight: 500,
    letterSpacing: "0.2em",
    color: alpha(CREAM, 0.94),
    display: "inline-block",
    mb: { xs: 2.5, md: 3 },
  },
  title: {
    color: CREAM,
    fontSize: "inherit",
    lineHeight: 0.9,
    textWrap: "balance",
  },
  titleScript: {
    fontFamily: "var(--font-display), Georgia, serif",
    fontStyle: "italic",
    fontWeight: 500,
    fontSize: { xs: "3.45rem", sm: "5rem", md: "7rem", lg: "8.15rem" },
  },
  titleRoman: {
    display: { xs: "block", md: "inline" },
    fontFamily: "var(--font-body), system-ui, sans-serif",
    fontStyle: "normal",
    fontWeight: 500,
    textTransform: "uppercase",
    letterSpacing: { xs: "0.03em", md: "0.01em" },
    fontSize: { xs: "1.65rem", sm: "2.25rem", md: "3.1rem", lg: "3.8rem" },
  },
  tagline: {
    mt: { xs: 3, md: 3.5 },
    mx: "auto",
    maxWidth: "58ch",
    color: alpha(CREAM, 0.96),
    fontSize: { xs: "1rem", md: "1.12rem" },
    fontWeight: 500,
    lineHeight: 1.7,
  },
  cta: {
    mt: { xs: 3.5, md: 4 },
    backgroundColor: OCHRE,
    color: CREAM,
    px: 4.5,
    "&:hover": { backgroundColor: CREAM, color: BURGUNDY },
  },
  scrollCue: {
    ...TRACKED_CAPS,
    position: "absolute",
    bottom: { xs: 24, md: 28 },
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "center",
    gap: 1.5,
    color: alpha(CREAM, 0.6),
    fontSize: "0.52rem",
    whiteSpace: "nowrap",
  },
  scrollLine: {
    width: 28,
    height: "1px",
    backgroundColor: "currentColor",
  },
} as const;
