import { alpha } from "@mui/material/styles";
import { BURGUNDY, CREAM, OCHRE, TAUPE_DEEP, TRACKED_CAPS } from "@/theme";

export const homeWelcomeStyles = {
  root: {
    position: "relative",
    backgroundColor: CREAM,
    pt: { xs: 5, md: 7 },
    pb: { xs: 10, md: 16 },
    backgroundImage: `radial-gradient(${alpha(BURGUNDY, 0.08)} 0.55px, transparent 0.55px)`,
    backgroundSize: "5px 5px",
  },
  ribbon: {
    ...TRACKED_CAPS,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: { xs: 1.25, sm: 2.25 },
    textAlign: "center",
    fontSize: { xs: "0.56rem", sm: "0.65rem" },
    color: alpha(BURGUNDY, 0.66),
    borderTop: `1px solid ${alpha(BURGUNDY, 0.18)}`,
    borderBottom: `1px solid ${alpha(BURGUNDY, 0.18)}`,
    py: 2.25,
    mb: { xs: 8, md: 12 },
  },
  ribbonMark: {
    color: OCHRE,
    fontSize: "0.7rem",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1.04fr 0.96fr" },
    alignItems: "center",
    gap: { xs: 9, md: 12 },
  },
  collage: {
    position: "relative",
    minHeight: { xs: 500, sm: 650, md: 720 },
  },
  mainImage: {
    position: "absolute",
    inset: { xs: "0 14% 8% 0", md: "0 16% 7% 0" },
    overflow: "hidden",
    borderRadius: "48% 48% 10px 10px / 26% 26% 10px 10px",
    "& picture, & img": { width: "100%", height: "100%", objectFit: "cover" },
  },
  accentImage: {
    position: "absolute",
    width: { xs: "46%", md: "45%" },
    aspectRatio: "1 / 1",
    right: 0,
    bottom: 0,
    borderRadius: "50%",
    overflow: "hidden",
    border: { xs: `7px solid ${CREAM}`, md: `10px solid ${CREAM}` },
    backgroundColor: TAUPE_DEEP,
    "& picture, & img": { width: "100%", height: "100%", objectFit: "cover" },
  },
  locationSeal: {
    ...TRACKED_CAPS,
    position: "absolute",
    top: { xs: "5%", md: "8%" },
    right: { xs: "0", md: "1%" },
    width: { xs: 112, md: 132 },
    aspectRatio: "1 / 1",
    borderRadius: "50%",
    backgroundColor: OCHRE,
    color: CREAM,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    gap: 0.75,
    fontSize: { xs: "0.45rem", md: "0.52rem" },
    lineHeight: 1.35,
    px: 2,
    "& strong": {
      fontFamily: "var(--font-display), Georgia, serif",
      fontStyle: "italic",
      fontWeight: 300,
      fontSize: { xs: "1.5rem", md: "1.8rem" },
      letterSpacing: 0,
      textTransform: "none",
    },
  },
  bodyStack: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 2.5,
  },
  body: {
    color: alpha(BURGUNDY, 0.76),
    maxWidth: "56ch",
  },
  link: {
    ...TRACKED_CAPS,
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    color: BURGUNDY,
    fontSize: "0.66rem",
    borderBottom: `1px solid ${alpha(BURGUNDY, 0.5)}`,
    pb: 1,
    mt: 1.5,
    transition: "gap 260ms ease, color 260ms ease",
    "&:hover": { gap: 3, color: OCHRE },
  },
} as const;
