import { alpha } from "@mui/material/styles";
import { BURGUNDY, CREAM, OCHRE, TRACKED_CAPS } from "@/theme";

export const homeServicesStyles = {
  grid: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "0.94fr 1.06fr" },
    alignItems: "center",
    gap: { xs: 9, md: 11 },
  },
  collage: {
    position: "relative",
    minHeight: { xs: 500, sm: 650, md: 760 },
  },
  mainImage: {
    position: "absolute",
    inset: { xs: "0 10% 6% 0", md: "0 11% 6% 0" },
    overflow: "hidden",
    borderRadius: "10px 90px 10px 90px",
    "& picture, & img": { width: "100%", height: "100%", objectFit: "cover" },
  },
  accentImage: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: { xs: "48%", md: "46%" },
    aspectRatio: "1 / 1",
    borderRadius: "50%",
    overflow: "hidden",
    border: { xs: `7px solid ${CREAM}`, md: `10px solid ${CREAM}` },
    "& picture, & img": { width: "100%", height: "100%", objectFit: "cover" },
  },
  imageCaption: {
    ...TRACKED_CAPS,
    position: "absolute",
    left: { xs: 16, md: 24 },
    bottom: { xs: 28, md: 36 },
    maxWidth: "20ch",
    backgroundColor: OCHRE,
    color: CREAM,
    px: 2.5,
    py: 1.75,
    fontSize: "0.55rem",
    lineHeight: 1.6,
  },
  content: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  list: {
    width: "100%",
    mt: { xs: 5, md: 6 },
    borderTop: `1px solid ${alpha(BURGUNDY, 0.24)}`,
  },
  row: {
    display: "grid",
    gridTemplateColumns: "34px 1fr auto",
    gap: { xs: 1.5, md: 2.5 },
    alignItems: "start",
    py: { xs: 3, md: 3.5 },
    borderBottom: `1px solid ${alpha(BURGUNDY, 0.24)}`,
    color: BURGUNDY,
    transition: "color 260ms ease, padding-left 260ms ease",
    "&:hover": { color: OCHRE, pl: 1 },
  },
  number: {
    ...TRACKED_CAPS,
    fontSize: "0.55rem",
    color: alpha(BURGUNDY, 0.52),
    pt: 0.9,
  },
  rowBody: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    gap: 1.25,
  },
  title: {
    fontFamily: "var(--font-body), system-ui, sans-serif",
    fontWeight: 300,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    fontSize: { xs: "1.05rem", md: "1.25rem" },
    lineHeight: 1.35,
  },
  summary: {
    maxWidth: "54ch",
    color: alpha(BURGUNDY, 0.7),
    fontSize: "0.86rem",
    lineHeight: 1.7,
  },
  price: {
    ...TRACKED_CAPS,
    color: alpha(BURGUNDY, 0.58),
    fontSize: "0.54rem",
  },
  plus: {
    fontFamily: "var(--font-body), system-ui, sans-serif",
    fontWeight: 300,
    fontSize: "1.8rem",
    lineHeight: 1,
  },
  allServices: {
    ...TRACKED_CAPS,
    display: "inline-flex",
    alignItems: "center",
    gap: 2,
    mt: 4,
    fontSize: "0.64rem",
    borderBottom: `1px solid ${alpha(BURGUNDY, 0.5)}`,
    pb: 1,
    transition: "gap 260ms ease, color 260ms ease",
    "&:hover": { gap: 3, color: OCHRE },
  },
} as const;
