export const introStyles = {
  section: {
    position: "relative",
    overflow: "hidden",
    py: { xs: 9, md: 14 },
    bgcolor: "background.default",
  },
  backgroundWord: {
    position: "absolute",
    top: { xs: 30, md: 60 },
    right: { xs: -80, md: -30 },
    color: "rgba(36, 69, 58, 0.04)",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "7rem", md: "14rem" },
    fontWeight: 700,
    letterSpacing: "-0.08em",
    lineHeight: 0.8,
    pointerEvents: "none",
  },
  grid: {
    position: "relative",
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "0.9fr 1.1fr" },
    gap: { xs: 7, md: 11 },
    alignItems: "center",
  },
  imageColumn: {
    position: "relative",
    pr: { xs: 3, sm: 8, md: 3 },
    pb: { xs: 3, sm: 7, md: 6 },
  },
  signImage: {
    width: "100%",
    aspectRatio: "4 / 5",
    display: "block",
    objectFit: "cover",
    borderRadius: "50% 50% 4px 4px / 10% 10% 4px 4px",
    boxShadow: "0 28px 80px rgba(45, 50, 43, 0.18)",
  },
  photoCard: {
    position: "absolute",
    right: { xs: 0, sm: 12, md: -30 },
    bottom: { xs: 0, sm: 0, md: 0 },
    width: { xs: 145, sm: 190, md: 205 },
    p: 1.25,
    bgcolor: "#FFFDF7",
    boxShadow: "0 18px 55px rgba(24, 41, 34, 0.22)",
    transform: "rotate(2deg)",
  },
  pastorImage: {
    width: "100%",
    aspectRatio: "4 / 3",
    display: "block",
    objectFit: "cover",
    filter: "saturate(0.82)",
  },
  photoCaption: {
    pt: 1,
    color: "text.secondary",
    fontSize: "0.67rem",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textAlign: "center",
    textTransform: "uppercase",
  },
  content: {
    position: "relative",
    zIndex: 1,
  },
  title: {
    mb: 3,
    maxWidth: 680,
    fontSize: { xs: "2.55rem", sm: "3.3rem", md: "4rem" },
    lineHeight: 1.06,
  },
  body: {
    mb: 2.5,
    maxWidth: 650,
    color: "text.secondary",
    fontSize: { xs: "1rem", md: "1.08rem" },
    lineHeight: 1.85,
  },
  quote: {
    mt: 4.5,
    pl: 3,
    borderLeft: "3px solid",
    borderColor: "secondary.main",
  },
  quoteText: {
    color: "primary.main",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "1.2rem", md: "1.45rem" },
    fontWeight: 600,
    fontStyle: "italic",
    lineHeight: 1.55,
  },
  quoteAttribution: {
    mt: 1.25,
    color: "text.secondary",
    fontSize: "0.72rem",
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
} as const;
