export const ministriesStyles = {
  section: {
    position: "relative",
    py: { xs: 9, md: 14 },
    overflow: "hidden",
    bgcolor: "#EEE5D5",
    backgroundImage:
      "linear-gradient(90deg, rgba(36,69,58,0.035) 1px, transparent 1px), linear-gradient(rgba(36,69,58,0.035) 1px, transparent 1px)",
    backgroundSize: "34px 34px",
  },
  cards: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "repeat(3, 1fr)" },
    gap: { xs: 2, md: 2.5 },
  },
  card: {
    position: "relative",
    minHeight: { xs: 315, md: 385 },
    p: { xs: 3.5, md: 4 },
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    border: "1px solid rgba(36, 69, 58, 0.14)",
    bgcolor: "rgba(255, 253, 247, 0.86)",
    boxShadow: "0 12px 45px rgba(51, 57, 48, 0.06)",
    transition: "transform 240ms ease, box-shadow 240ms ease",
    "&:hover": {
      boxShadow: "0 22px 55px rgba(51, 57, 48, 0.12)",
      transform: "translateY(-7px)",
    },
  },
  number: {
    position: "absolute",
    top: -20,
    right: -5,
    color: "rgba(184, 92, 56, 0.09)",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: "8rem",
    fontWeight: 700,
    lineHeight: 1,
  },
  icon: {
    width: 54,
    height: 54,
    mb: "auto",
    display: "grid",
    placeItems: "center",
    borderRadius: "50%",
    bgcolor: "primary.main",
    color: "#FFF9EE",
  },
  title: {
    mt: 5,
    mb: 2,
    color: "primary.dark",
    fontSize: { xs: "1.65rem", md: "1.85rem" },
  },
  body: {
    color: "text.secondary",
    fontSize: "0.96rem",
    lineHeight: 1.75,
  },
  footer: {
    mt: { xs: 5, md: 6 },
    p: { xs: 3, md: 4 },
    display: "flex",
    flexDirection: { xs: "column", sm: "row" },
    alignItems: { xs: "flex-start", sm: "center" },
    justifyContent: "space-between",
    gap: 3,
    bgcolor: "primary.main",
    color: "primary.contrastText",
  },
  footerTitle: {
    mb: 0.5,
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "1.3rem", md: "1.6rem" },
    fontWeight: 600,
  },
  footerBody: {
    color: "rgba(255, 249, 238, 0.68)",
    fontSize: "0.9rem",
  },
  prayerButton: {
    flexShrink: 0,
    borderColor: "rgba(255, 249, 238, 0.45)",
    color: "#FFF9EE",
    "&:hover": {
      borderColor: "#FFF9EE",
      bgcolor: "rgba(255, 255, 255, 0.06)",
    },
  },
} as const;
