export const styles = {
  section: {
    bgcolor: "#ffffff",
  },
  headingRow: {
    alignItems: { md: "end" },
    display: "flex",
    flexDirection: { xs: "column", md: "row" },
    justifyContent: "space-between",
    mb: { xs: 5, md: 7 },
  },
  heading: {
    maxWidth: "680px",
  },
  intro: {
    mt: { xs: 2.5, md: 0 },
  },
  beforeAfter: {
    bgcolor: "primary.dark",
    borderRadius: "30px",
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "0.68fr 1fr" },
    mb: 3,
    overflow: "hidden",
  },
  beforeAfterCopy: {
    alignItems: "flex-start",
    color: "#ffffff",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    p: { xs: 4, sm: 5, lg: 7 },
  },
  projectNumber: {
    color: "secondary.main",
    fontSize: "0.7rem",
    fontWeight: 800,
    letterSpacing: "0.16em",
    mb: 2,
    textTransform: "uppercase",
  },
  beforeAfterHeading: {
    color: "#ffffff",
    fontSize: { xs: "2.6rem", lg: "3.6rem" },
    maxWidth: "430px",
  },
  beforeAfterText: {
    color: "rgba(255, 255, 255, 0.67)",
    fontSize: "0.92rem",
    lineHeight: 1.75,
    mt: 2,
    maxWidth: "410px",
  },
  beforeAfterImages: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    minHeight: { xs: "360px", sm: "500px", md: "620px" },
  },
  comparisonImage: {
    overflow: "hidden",
    position: "relative",
  },
  image: {
    height: "100%",
    inset: 0,
    objectFit: "cover",
    position: "absolute",
    width: "100%",
  },
  imageLabel: {
    backdropFilter: "blur(9px)",
    bgcolor: "rgba(18, 51, 36, 0.82)",
    borderRadius: "999px",
    bottom: 18,
    color: "#ffffff",
    fontSize: "0.65rem",
    fontWeight: 800,
    left: 18,
    letterSpacing: "0.12em",
    px: 1.5,
    py: 0.8,
    position: "absolute",
    textTransform: "uppercase",
  },
  gallery: {
    display: "grid",
    gap: 3,
    gridAutoRows: { xs: "320px", md: "270px" },
    gridTemplateColumns: { xs: "1fr", sm: "1fr 1fr", md: "repeat(4, 1fr)" },
  },
  project: {
    borderRadius: "24px",
    gridColumn: { xs: "span 1", md: "span 1" },
    overflow: "hidden",
    position: "relative",
    "&[data-size='large']": {
      gridColumn: { xs: "span 1", sm: "span 2" },
    },
    "&:hover img": {
      transform: "scale(1.045)",
    },
  },
  projectImage: {
    height: "100%",
    objectFit: "cover",
    transition: "transform 500ms ease",
    width: "100%",
  },
  projectOverlay: {
    background:
      "linear-gradient(180deg, transparent 45%, rgba(18, 51, 36, 0.78) 100%)",
    inset: 0,
    position: "absolute",
  },
  projectLabel: {
    bottom: 20,
    color: "#ffffff",
    fontFamily: '"Iowan Old Style", "Baskerville", Georgia, serif',
    fontSize: "1.3rem",
    fontWeight: 600,
    left: 22,
    position: "absolute",
  },
};
