export const roundPenStyles = {
  section: {
    position: "relative",
    overflow: "hidden",
    py: { xs: 9, md: 14 },
    bgcolor: "primary.dark",
    color: "primary.contrastText",
    "&::before": {
      position: "absolute",
      top: -180,
      right: -120,
      width: 500,
      height: 500,
      border: "1px solid rgba(255, 249, 238, 0.08)",
      borderRadius: "50%",
      content: '""',
    },
    "&::after": {
      position: "absolute",
      top: -105,
      right: -45,
      width: 350,
      height: 350,
      border: "1px solid rgba(255, 249, 238, 0.08)",
      borderRadius: "50%",
      content: '""',
    },
  },
  grid: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1.08fr 0.92fr" },
    gap: { xs: 8, md: 11 },
    alignItems: "center",
  },
  gallery: {
    position: "relative",
    minHeight: { xs: 420, sm: 560, md: 620 },
  },
  mainImageWrap: {
    position: "absolute",
    inset: { xs: "0 28px 75px 0", sm: "0 100px 85px 0", md: "0 80px 95px 0" },
    overflow: "hidden",
    border: "1px solid rgba(255, 249, 238, 0.18)",
    bgcolor: "#0D241E",
  },
  mainImage: {
    width: "100%",
    height: "100%",
    display: "block",
    objectFit: "cover",
    filter: "saturate(0.7) sepia(0.08)",
    transition: "transform 600ms ease",
    "&:hover": {
      transform: "scale(1.025)",
    },
  },
  secondaryImageWrap: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: { xs: "56%", sm: "49%", md: "52%" },
    p: 1.25,
    bgcolor: "#F2E8D8",
    boxShadow: "0 22px 65px rgba(0, 0, 0, 0.38)",
    transform: "rotate(-2.5deg)",
  },
  secondaryImage: {
    width: "100%",
    aspectRatio: "4 / 3",
    display: "block",
    objectFit: "cover",
    filter: "saturate(0.72)",
  },
  secondaryCaption: {
    pt: 1,
    color: "#526057",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "0.65rem", sm: "0.8rem" },
    fontStyle: "italic",
    textAlign: "center",
  },
  content: {
    position: "relative",
    zIndex: 1,
  },
  title: {
    mb: 3,
    color: "#FFF9EE",
    fontSize: { xs: "2.55rem", sm: "3.2rem", md: "4rem" },
    lineHeight: 1.06,
  },
  body: {
    mb: 2.5,
    color: "rgba(255, 249, 238, 0.72)",
    fontSize: { xs: "1rem", md: "1.08rem" },
    lineHeight: 1.8,
  },
  highlight: {
    mt: 4,
    py: 2.5,
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    gap: 2,
    borderTop: "1px solid rgba(255, 249, 238, 0.15)",
    borderBottom: "1px solid rgba(255, 249, 238, 0.15)",
  },
  highlightIcon: {
    width: 48,
    height: 48,
    display: "grid",
    placeItems: "center",
    borderRadius: "50%",
    bgcolor: "secondary.main",
    color: "white",
  },
  highlightTitle: {
    mb: 0.5,
    color: "#FFF9EE",
    fontWeight: 700,
  },
  highlightBody: {
    color: "rgba(255, 249, 238, 0.58)",
    fontSize: "0.9rem",
    lineHeight: 1.6,
  },
  link: {
    mt: 4,
    color: "#E8A27A",
    fontWeight: 800,
    textDecoration: "none",
    "&:hover": {
      color: "#FFC09A",
    },
  },
} as const;
