export const styles = {
  band: {
    bgcolor: "primary.dark",
    color: "#ffffff",
    overflow: "hidden",
    py: { xs: 5.5, md: 6.5 },
    position: "relative",
  },
  decor: {
    border: "1px solid rgba(217, 170, 85, 0.22)",
    borderRadius: "50%",
    height: "280px",
    position: "absolute",
    right: "-85px",
    top: "-140px",
    width: "280px",
  },
  content: {
    alignItems: { xs: "flex-start", lg: "center" },
    display: "flex",
    flexDirection: { xs: "column", lg: "row" },
    gap: { xs: 3, lg: 5 },
    justifyContent: "space-between",
    position: "relative",
  },
  headingWrap: {
    alignItems: "center",
    display: "flex",
    flex: "0 0 auto",
    gap: 1.25,
  },
  pin: {
    alignItems: "center",
    bgcolor: "secondary.main",
    borderRadius: "50%",
    color: "primary.dark",
    display: "flex",
    height: "44px",
    justifyContent: "center",
    width: "44px",
  },
  heading: {
    color: "#ffffff",
    fontFamily: '"Iowan Old Style", "Baskerville", Georgia, serif',
    fontSize: { xs: "1.7rem", md: "2rem" },
    fontWeight: 600,
  },
  subheading: {
    color: "rgba(255, 255, 255, 0.58)",
    fontSize: "0.7rem",
    fontWeight: 700,
    letterSpacing: "0.09em",
    mt: 0.25,
    textTransform: "uppercase",
  },
  cities: {
    display: "flex",
    flexWrap: "wrap",
    gap: 1,
  },
  city: {
    border: "1px solid rgba(255, 255, 255, 0.16)",
    borderRadius: "999px",
    color: "rgba(255, 255, 255, 0.9)",
    fontSize: "0.76rem",
    fontWeight: 700,
    px: 1.75,
    py: 1,
  },
};
