export const visitStyles = {
  section: {
    position: "relative",
    overflow: "hidden",
    py: { xs: 9, md: 13 },
    bgcolor: "secondary.main",
    color: "white",
    "&::before": {
      position: "absolute",
      inset: 0,
      opacity: 0.14,
      backgroundImage:
        "repeating-radial-gradient(ellipse at 85% 40%, transparent 0 28px, #FFF9EE 29px 30px, transparent 31px 52px)",
      content: '""',
      pointerEvents: "none",
    },
  },
  grid: {
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { xs: "1fr", md: "1fr 0.82fr" },
    gap: { xs: 6, md: 9 },
    alignItems: "center",
  },
  kicker: {
    display: "inline-flex",
    alignItems: "center",
    gap: 1.25,
    mb: 2.5,
    color: "rgba(255,255,255,0.78)",
    fontSize: "0.75rem",
    fontWeight: 800,
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    "&::before": {
      width: 34,
      height: 2,
      bgcolor: "currentColor",
      content: '""',
    },
  },
  title: {
    maxWidth: 720,
    mb: 3,
    color: "white",
    fontSize: { xs: "2.65rem", sm: "3.5rem", md: "4.35rem" },
    lineHeight: 1.04,
  },
  body: {
    maxWidth: 650,
    mb: 4,
    color: "rgba(255,255,255,0.78)",
    fontSize: { xs: "1rem", md: "1.08rem" },
    lineHeight: 1.8,
  },
  expectations: {
    display: "grid",
    gridTemplateColumns: { xs: "1fr", sm: "repeat(3, 1fr)" },
    gap: 2,
  },
  expectation: {
    pt: 2,
    borderTop: "1px solid rgba(255,255,255,0.3)",
  },
  expectationTitle: {
    mb: 0.5,
    fontWeight: 800,
  },
  expectationBody: {
    color: "rgba(255,255,255,0.68)",
    fontSize: "0.82rem",
    lineHeight: 1.55,
  },
  card: {
    p: { xs: 3.5, sm: 5 },
    border: "1px solid rgba(255,255,255,0.16)",
    bgcolor: "primary.dark",
    boxShadow: "0 28px 80px rgba(78, 30, 17, 0.28)",
  },
  icon: {
    width: 58,
    height: 58,
    mb: 3,
    display: "grid",
    placeItems: "center",
    borderRadius: "50%",
    bgcolor: "rgba(255,255,255,0.09)",
    color: "#E8A27A",
  },
  cardKicker: {
    mb: 1,
    color: "#E8A27A",
    fontSize: "0.72rem",
    fontWeight: 800,
    letterSpacing: "0.13em",
    textTransform: "uppercase",
  },
  address: {
    mb: 1.5,
    color: "#FFF9EE",
    fontFamily: '"Bitter", Georgia, serif',
    fontSize: { xs: "1.7rem", sm: "2rem" },
    fontWeight: 600,
    lineHeight: 1.28,
  },
  cardDetail: {
    mb: 0.5,
    color: "rgba(255,249,238,0.68)",
    fontSize: "0.93rem",
  },
  actions: {
    mt: 4,
    display: "flex",
    flexDirection: "column",
    gap: 1.25,
  },
  directionsButton: {
    bgcolor: "#FFF9EE",
    color: "primary.dark",
    "&:hover": {
      bgcolor: "#F0E2CE",
    },
  },
  callButton: {
    borderColor: "rgba(255,249,238,0.36)",
    color: "#FFF9EE",
    "&:hover": {
      borderColor: "#FFF9EE",
      bgcolor: "rgba(255,255,255,0.05)",
    },
  },
} as const;
